# Generated by Django 6.0.1 on 2026-04-25 02:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('role', models.CharField(blank=True, default='', max_length=120)),
                ('quote', models.TextField(blank=True, default='')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='program',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_title',
            field=models.CharField(blank=True, default='About Us', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admissions_overview',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admissions_requirements',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admissions_title',
            field=models.CharField(blank=True, default='Admissions', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_intro',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_title',
            field=models.CharField(blank=True, default='Contact Us', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_text',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(blank=True, default='Welcome to Prime Choice Kids Care', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_embed_code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mission_text',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mission_title',
            field=models.CharField(blank=True, default='Mission', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notification_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='opening_hours',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_from_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_host',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vision_text',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vision_title',
            field=models.CharField(blank=True, default='Vision', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='program',
            name='age_group',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_us',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, default='info@primechoicekids.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='location',
            field=models.CharField(blank=True, default='New Baakoyeden', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone1',
            field=models.CharField(blank=True, default='0541961061', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone2',
            field=models.CharField(blank=True, default='0244303267', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='school_name',
            field=models.CharField(blank=True, default='Prime Choice Kids Care', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(blank=True, default='Join us and be part of shaping young minds!', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='why_choose_us',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Describe why parents should choose the school'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='qualifications',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
