# Generated by Django 6.0.1 on 2026-04-25 03:03

from django.db import migrations, models
from django.utils.text import slugify


def populate_news_slugs(apps, schema_editor):
    NewsEvent = apps.get_model('core', 'NewsEvent')
    used = set()
    for item in NewsEvent.objects.all().order_by('id'):
        base = slugify(item.title or 'news-event')[:200] or 'news-event'
        candidate = base
        counter = 2
        while candidate in used:
            candidate = f'{base}-{counter}'
            counter += 1
        used.add(candidate)
        item.slug = candidate
        item.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newsevent_statcounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('call', 'Call'), ('whatsapp', 'WhatsApp'), (
                    'cta', 'CTA'), ('social', 'Social'), ('nav', 'Navigation')], default='cta', max_length=20)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('target_url', models.CharField(
                    blank=True, default='', max_length=500)),
                ('source_page', models.CharField(
                    blank=True, default='', max_length=200)),
                ('ip_address', models.CharField(
                    blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(
                    blank=True, default='', max_length=300)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.AddField(
            model_name='newsevent',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=220),
        ),
        migrations.RunPython(populate_news_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='newsevent',
            name='slug',
            field=models.SlugField(
                blank=True, default='', max_length=220, unique=True),
        ),
    ]
