# Generated by Django 6.0.1 on 2026-04-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_clickmetric_newsevent_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('role', models.CharField(blank=True, default='', help_text='Job title or position (e.g., Principal, Teacher, Caregiver)', max_length=120)),
                ('bio', models.TextField(blank=True, default='', help_text='Short biography or description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
