# Generated by Django 6.0.1 on 2026-04-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_staffmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pinterest',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_url',
            field=models.URLField(blank=True, default='', help_text='WhatsApp business profile or group URL'),
        ),
    ]
