# Generated by Django 6.0.1 on 2026-04-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesettings_db_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='programs/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='staff/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='avatar',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='testimonials/'),
        ),
    ]
